import type { WordPair } from './types.js';

/**
 * Paires de mots pour le jeu Imposteur.
 * motCitoyens = mot reçu par les Citoyens
 * motImposteur = mot reçu par l'Imposteur (proche mais différent)
 */
export const WORD_PAIRS: WordPair[] = [
  { motCitoyens: 'Pizza', motImposteur: 'Burger' },
  { motCitoyens: 'Chien', motImposteur: 'Loup' },
  { motCitoyens: 'Chat', motImposteur: 'Tigre' },
  { motCitoyens: 'Mer', motImposteur: 'Océan' },
  { motCitoyens: 'Soleil', motImposteur: 'Lune' },
  { motCitoyens: 'Café', motImposteur: 'Thé' },
  { motCitoyens: 'Train', motImposteur: 'Métro' },
  { motCitoyens: 'Avion', motImposteur: 'Hélicoptère' },
  { motCitoyens: 'Pomme', motImposteur: 'Poire' },
  { motCitoyens: 'Banane', motImposteur: 'Mangue' },
  { motCitoyens: 'Neige', motImposteur: 'Glace' },
  { motCitoyens: 'Hôpital', motImposteur: 'Pharmacie' },
  { motCitoyens: 'École', motImposteur: 'Université' },
  { motCitoyens: 'Stylo', motImposteur: 'Crayon' },
  { motCitoyens: 'Téléphone', motImposteur: 'Radio' },
  { motCitoyens: 'Guitare', motImposteur: 'Violon' },
  { motCitoyens: 'Football', motImposteur: 'Rugby' },
  { motCitoyens: 'Tennis', motImposteur: 'Badminton' },
  { motCitoyens: 'Camion', motImposteur: 'Bus' },
  { motCitoyens: 'Vélo', motImposteur: 'Moto' },
  { motCitoyens: 'Sandwich', motImposteur: 'Tacos' },
  { motCitoyens: 'Fromage', motImposteur: 'Beurre' },
  { motCitoyens: 'Jardin', motImposteur: 'Forêt' },
  { motCitoyens: 'Rivière', motImposteur: 'Lac' },
  { motCitoyens: 'Montagne', motImposteur: 'Colline' },
  { motCitoyens: 'Roi', motImposteur: 'Président' },
  { motCitoyens: 'Policier', motImposteur: 'Détective' },
  { motCitoyens: 'Peinture', motImposteur: 'Dessin' },
  { motCitoyens: 'Film', motImposteur: 'Série' },
  { motCitoyens: 'Robot', motImposteur: 'Humain' },
  // Lieux & situations
  { motCitoyens: 'Mariage', motImposteur: 'Enterrement' },
  { motCitoyens: 'Hôpital', motImposteur: 'Hôtel' },
  { motCitoyens: 'Aéroport', motImposteur: 'Gare' },
  { motCitoyens: 'Bibliothèque', motImposteur: 'Musée' },
  { motCitoyens: 'Casino', motImposteur: 'Église' },
  { motCitoyens: 'Camping', motImposteur: 'Armée' },
  { motCitoyens: 'Piscine', motImposteur: 'Prison' },
  { motCitoyens: 'Restaurant', motImposteur: 'Tribunal' },
  { motCitoyens: 'Zoo', motImposteur: 'École' },
  { motCitoyens: 'Ascenseur', motImposteur: 'Sous-marin' },
  { motCitoyens: 'Concert', motImposteur: 'Manifestation' },
  { motCitoyens: 'Stade', motImposteur: 'Usine' },
  { motCitoyens: 'Théâtre', motImposteur: 'Tribunal' },
  { motCitoyens: 'Croisière', motImposteur: 'Maison de retraite' },
  { motCitoyens: 'Colonie de vacances', motImposteur: 'Prison' },
  { motCitoyens: 'Réunion', motImposteur: 'Cours magistral' },
  { motCitoyens: 'Entretien d\'embauche', motImposteur: 'Premier rendez-vous' },
  { motCitoyens: 'Mariage', motImposteur: 'Spectacle' },
  { motCitoyens: 'Déménagement', motImposteur: 'Cambriolage' },
  { motCitoyens: 'Soldes', motImposteur: 'Braquage' },
  // Nature & météo
  { motCitoyens: 'Orage', motImposteur: 'Concert' },
  { motCitoyens: 'Tempête', motImposteur: 'Dispute' },
  { motCitoyens: 'Brouillard', motImposteur: 'Rêve' },
  { motCitoyens: 'Désert', motImposteur: 'Sauna' },
  { motCitoyens: 'Feu d\'artifice', motImposteur: 'Victoire' },
  { motCitoyens: 'Avalanche', motImposteur: 'Embouteillage' },
  { motCitoyens: 'Volcan', motImposteur: 'Révolution' },
  { motCitoyens: 'Tornade', motImposteur: 'Danse' },
  { motCitoyens: 'Arc-en-ciel', motImposteur: 'Promesse' },
  { motCitoyens: 'Coucher de soleil', motImposteur: 'Fin de film' },
  { motCitoyens: 'Fourmilière', motImposteur: 'Open-space' },
  { motCitoyens: 'Ruche', motImposteur: 'Centre commercial' },
  { motCitoyens: 'Jungle', motImposteur: 'Internet' },
  { motCitoyens: 'Océan', motImposteur: 'Bibliothèque' },
  { motCitoyens: 'Montagne', motImposteur: 'Défi' },
  { motCitoyens: 'Rivière', motImposteur: 'Conversation' },
  { motCitoyens: 'Forêt', motImposteur: 'Labyrinthe' },
  { motCitoyens: 'Île', motImposteur: 'Secret' },
  { motCitoyens: 'Grotte', motImposteur: 'Refuge' },
  { motCitoyens: 'Désert', motImposteur: 'Silence' },
  // Personnages & archétypes
  { motCitoyens: 'Robot', motImposteur: 'Majordome' },
  { motCitoyens: 'Dragon', motImposteur: 'Patron' },
  { motCitoyens: 'Pirate', motImposteur: 'Entrepreneur' },
  { motCitoyens: 'Ninja', motImposteur: 'Espion' },
  { motCitoyens: 'Sorcier', motImposteur: 'Professeur' },
  { motCitoyens: 'Vampire', motImposteur: 'Influenceur' },
  { motCitoyens: 'Zombie', motImposteur: 'Fonctionnaire' },
  { motCitoyens: 'Chevalier', motImposteur: 'Policier' },
  { motCitoyens: 'Alien', motImposteur: 'Touriste' },
  { motCitoyens: 'Fantôme', motImposteur: 'Ex' },
  { motCitoyens: 'Banane', motImposteur: 'Boomerang' },
  { motCitoyens: 'Cactus', motImposteur: 'Belle-mère' },
  { motCitoyens: 'Pingouin', motImposteur: 'Comptable' },
  { motCitoyens: 'Licorne', motImposteur: 'Startup' },
  { motCitoyens: 'Dragon', motImposteur: 'Voisin' },
  { motCitoyens: 'Robot', motImposteur: 'Grand-père' },
  // Objets & métaphores
  { motCitoyens: 'Chaussette', motImposteur: 'Politique' },
  { motCitoyens: 'Parapluie', motImposteur: 'Optimisme' },
  { motCitoyens: 'Réfrigérateur', motImposteur: 'Philosophe' },
  { motCitoyens: 'Grille-pain', motImposteur: 'Dictateur' },
  { motCitoyens: 'Horloge', motImposteur: 'Professeur' },
  { motCitoyens: 'Miroir', motImposteur: 'Réseau social' },
  { motCitoyens: 'Clé', motImposteur: 'Solution' },
  { motCitoyens: 'Valise', motImposteur: 'Liberté' },
  { motCitoyens: 'Fenêtre', motImposteur: 'Opportunité' },
  { motCitoyens: 'Échelle', motImposteur: 'Ambition' },
  { motCitoyens: 'Bougie', motImposteur: 'Espoir' },
  { motCitoyens: 'Serrure', motImposteur: 'Secret' },
  { motCitoyens: 'Boussole', motImposteur: 'Conseiller' },
  { motCitoyens: 'Télécommande', motImposteur: 'Pouvoir' },
  { motCitoyens: 'Roi', motImposteur: 'PDG' },
  { motCitoyens: 'Ministre', motImposteur: 'Chef d\'orchestre' },
  { motCitoyens: 'Détective', motImposteur: 'Journaliste' },
  { motCitoyens: 'Avocat', motImposteur: 'Négociateur' },
  { motCitoyens: 'Pompier', motImposteur: 'Médecin' },
  { motCitoyens: 'Professeur', motImposteur: 'Jardinier' },
  { motCitoyens: 'Astronaute', motImposteur: 'Explorateur' },
  { motCitoyens: 'Cuisinier', motImposteur: 'Chimiste' },
  { motCitoyens: 'Architecte', motImposteur: 'Romancier' },
  { motCitoyens: 'Magicien', motImposteur: 'Commercial' },
  { motCitoyens: 'Succès', motImposteur: 'Chance' },
  { motCitoyens: 'Courage', motImposteur: 'Folie' },
  { motCitoyens: 'Talent', motImposteur: 'Discipline' },
  { motCitoyens: 'Vérité', motImposteur: 'Miroir' },
  { motCitoyens: 'Mensonge', motImposteur: 'Maquillage' },
  { motCitoyens: 'Liberté', motImposteur: 'Solitude' },
  { motCitoyens: 'Richesse', motImposteur: 'Temps' },
  { motCitoyens: 'Pouvoir', motImposteur: 'Addiction' },
  { motCitoyens: 'Rêve', motImposteur: 'Projet' },
  { motCitoyens: 'Nostalgie', motImposteur: 'Parfum' },
  // Tech & modernité
  { motCitoyens: 'Netflix', motImposteur: 'Vacances' },
  { motCitoyens: 'Téléphone', motImposteur: 'Doudou' },
  { motCitoyens: 'Wi-Fi', motImposteur: 'Eau' },
  { motCitoyens: 'Batterie', motImposteur: 'Motivation' },
  { motCitoyens: 'GPS', motImposteur: 'Parent' },
  { motCitoyens: 'Mot de passe', motImposteur: 'Identité' },
  { motCitoyens: 'Smartphone', motImposteur: 'Couteau suisse' },
  { motCitoyens: 'Notification', motImposteur: 'Moustique' },
  { motCitoyens: 'Selfie', motImposteur: 'Autoportrait' },
  { motCitoyens: 'Algorithme', motImposteur: 'Destin' },
  { motCitoyens: 'Licorne', motImposteur: 'Impôts' },
  { motCitoyens: 'Banane', motImposteur: 'Dictateur' },
  { motCitoyens: 'Cactus', motImposteur: 'Influenceur' },
  { motCitoyens: 'Lama', motImposteur: 'Banquier' },
  { motCitoyens: 'Dragon', motImposteur: 'Concierge' },
  { motCitoyens: 'Yéti', motImposteur: 'Voisin' },
  { motCitoyens: 'Poulpe', motImposteur: 'Politicien' },
  { motCitoyens: 'Castor', motImposteur: 'PDG' },
  { motCitoyens: 'Paresseux', motImposteur: 'Fonctionnaire' },
  { motCitoyens: 'Chaussette', motImposteur: 'Révolution' },
  { motCitoyens: 'Grille-pain', motImposteur: 'Philosophe' },
  { motCitoyens: 'Parapluie', motImposteur: 'Rockstar' },
  { motCitoyens: 'Aspirateur', motImposteur: 'Vampire' },
  { motCitoyens: 'Cintre', motImposteur: 'Empereur' },
  { motCitoyens: 'Fourchette', motImposteur: 'Détective' },
  { motCitoyens: 'Balai', motImposteur: 'Influenceur' },
  { motCitoyens: 'Frigo', motImposteur: 'Magicien' },
  { motCitoyens: 'Oreiller', motImposteur: 'Président' },
  { motCitoyens: 'Télécommande', motImposteur: 'Dictature' },
  { motCitoyens: 'Clown', motImposteur: 'Banquier' },
  { motCitoyens: 'Pirate', motImposteur: 'Notaire' },
  { motCitoyens: 'Ninja', motImposteur: 'Bibliothécaire' },
  { motCitoyens: 'Sorcier', motImposteur: 'Comptable' },
  { motCitoyens: 'Chevalier', motImposteur: 'Commercial' },
  { motCitoyens: 'Vampire', motImposteur: 'Agent immobilier' },
  { motCitoyens: 'Zombie', motImposteur: 'Consultant' },
  { motCitoyens: 'Princesse', motImposteur: 'Mécanicien' },
  { motCitoyens: 'Roi', motImposteur: 'Livreur' },
  { motCitoyens: 'Reine', motImposteur: 'Chauffeur de bus' },
  // Nourriture & animaux
  { motCitoyens: 'Croissant', motImposteur: 'Haltère' },
  { motCitoyens: 'Saucisson', motImposteur: 'Trophée' },
  { motCitoyens: 'Cornichon', motImposteur: 'Influenceur' },
  { motCitoyens: 'Pastèque', motImposteur: 'Météorite' },
  { motCitoyens: 'Frite', motImposteur: 'Diplomate' },
  { motCitoyens: 'Burger', motImposteur: 'Philosophe' },
  { motCitoyens: 'Fromage', motImposteur: 'Rockstar' },
  { motCitoyens: 'Pizza', motImposteur: 'Astronaute' },
  { motCitoyens: 'Donut', motImposteur: 'Détective' },
  { motCitoyens: 'Ketchup', motImposteur: 'Poète' },
  { motCitoyens: 'Canard', motImposteur: 'Avocat' },
  { motCitoyens: 'Pigeon', motImposteur: 'Ministre' },
  { motCitoyens: 'Autruche', motImposteur: 'Professeur' },
  { motCitoyens: 'Girafe', motImposteur: 'DJ' },
  { motCitoyens: 'Kangourou', motImposteur: 'Policier' },
  { motCitoyens: 'Lama', motImposteur: 'Humoriste' },
  { motCitoyens: 'Chèvre', motImposteur: 'Youtubeur' },
  { motCitoyens: 'Paon', motImposteur: 'Acteur' },
  { motCitoyens: 'Ours', motImposteur: 'Jardinier' },
  { motCitoyens: 'Mouette', motImposteur: 'Journaliste' },
  { motCitoyens: 'Bulle', motImposteur: 'Secret' },
  { motCitoyens: 'Brouillard', motImposteur: 'Mensonge' },
  { motCitoyens: 'Arc-en-ciel', motImposteur: 'Contrat' },
  { motCitoyens: 'Tempête', motImposteur: 'Réunion' },
  { motCitoyens: 'Volcan', motImposteur: 'Anniversaire' },
  { motCitoyens: 'Avalanche', motImposteur: 'Mariage' },
  { motCitoyens: 'Éclair', motImposteur: 'Réponse' },
  { motCitoyens: 'Désert', motImposteur: 'Wi-Fi' },
  { motCitoyens: 'Glacier', motImposteur: 'Motivation' },
  { motCitoyens: 'Tornade', motImposteur: 'Rumeur' },
  { motCitoyens: 'Skateboard', motImposteur: 'Diplomatie' },
  { motCitoyens: 'Trottinette', motImposteur: 'Aristocratie' },
  { motCitoyens: 'Sous-marin', motImposteur: 'Colocation' },
  { motCitoyens: 'Trampoline', motImposteur: 'Bourse' },
  { motCitoyens: 'Montgolfière', motImposteur: 'Bureaucratie' },
  { motCitoyens: 'Fusée', motImposteur: 'Retraite' },
  { motCitoyens: 'Vélo', motImposteur: 'Nostalgie' },
  { motCitoyens: 'Hélicoptère', motImposteur: 'Commérage' },
  { motCitoyens: 'Tracteur', motImposteur: 'Élégance' },
  { motCitoyens: 'Canoë', motImposteur: 'Ambition' },
  { motCitoyens: 'Selfie', motImposteur: 'Égocentrisme' },
  { motCitoyens: 'Smartphone', motImposteur: 'Doudou' },
  { motCitoyens: 'GPS', motImposteur: 'Grand-mère' },
  { motCitoyens: 'Mot de passe', motImposteur: 'Trésor' },
  { motCitoyens: 'Batterie', motImposteur: 'Courage' },
  { motCitoyens: 'Wi-Fi', motImposteur: 'Religion' },
  { motCitoyens: 'Drone', motImposteur: 'Curiosité' },
  { motCitoyens: 'Casque', motImposteur: 'Timidité' },
  { motCitoyens: 'Chausson', motImposteur: 'Courage' },
  { motCitoyens: 'Pyjama', motImposteur: 'Leadership' },
  { motCitoyens: 'Brosse à dents', motImposteur: 'Discipline' },
  { motCitoyens: 'Savon', motImposteur: 'Diplomatie' },
  { motCitoyens: 'Moustache', motImposteur: 'Autorité' },
  { motCitoyens: 'Pantoufle', motImposteur: 'Prestige' },
  { motCitoyens: 'Peigne', motImposteur: 'Stratégie' },
  { motCitoyens: 'Serviette', motImposteur: 'Mystère' },
  { motCitoyens: 'Tasse', motImposteur: 'Sagesse' },
  { motCitoyens: 'Valise', motImposteur: 'Espoir' },
  { motCitoyens: 'Monstre', motImposteur: 'Bébé' },
  { motCitoyens: 'Dinosaure', motImposteur: 'Startuppeur' },
  { motCitoyens: 'Kraken', motImposteur: 'Syndic' },
  { motCitoyens: 'Licorne', motImposteur: 'Commercial' },
  { motCitoyens: 'Sorcière', motImposteur: 'Voisine' },
  { motCitoyens: 'Dragon', motImposteur: 'Beau-père' },
  { motCitoyens: 'Yéti', motImposteur: 'Influenceur' },
];

/** Retourne une paire de mots aléatoire */
export function getRandomWordPair(): WordPair {
  return WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
}
